### ISSUE TITLE
Linux dll not found exception..

### ISSUE THREAD

**Issue by SB16Tech** [NotNotTech/Raylib-CsLo#31]
```
Exception has occurred: CLR/System.DllNotFoundException
An unhandled exception of type 'System.DllNotFoundException' occurred in Raylib-CsLo.dll: 'Unable to load shared library 'raylib' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable: 
/home/shadowblitz16/Documents/source/C#/GameSharp/GameSharp/bin/Debug/net7.0/runtimes/linux-x64/native/raylib.so: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.1/raylib.so: cannot open shared object file: No such file or directory
/home/shadowblitz16/Documents/source/C#/GameSharp/GameSharp/bin/Debug/net7.0/raylib.so: cannot open shared object file: No such file or directory
/lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by /home/shadowblitz16/Documents/source/C#/GameSharp/GameSharp/bin/Debug/net7.0/runtimes/linux-x64/native/libraylib.so)
/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.1/libraylib.so: cannot open shared object file: No such file or directory
/home/shadowblitz16/Documents/source/C#/GameSharp/GameSharp/bin/Debug/net7.0/libraylib.so: cannot open shared object file: No such file or directory
/home/shadowblitz16/Documents/source/C#/GameSharp/GameSharp/bin/Debug/net7.0/runtimes/linux-x64/native/raylib: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.1/raylib: cannot open shared object file: No such file or directory
/home/shadowblitz16/Documents/source/C#/GameSharp/GameSharp/bin/Debug/net7.0/raylib: cannot open shared object file: No such file or directory
/home/shadowblitz16/Documents/source/C#/GameSharp/GameSharp/bin/Debug/net7.0/runtimes/linux-x64/native/libraylib: cannot open shared object file: No such file or directory
/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.1/libraylib: cannot open shared object file: No such file or directory
/home/shadowblitz16/Documents/source/C#/GameSharp/GameSharp/bin/Debug/net7.0/libraylib: cannot open shared object file: No such file or directory'
   at Raylib_CsLo.Raylib.SetConfigFlags(UInt32 flags)
   at Raylib_CsLo.Raylib.SetConfigFlags(ConfigFlags flags)
   at GameSharp.Windowing.Window..ctor() in /home/shadowblitz16/Documents/source/C#/GameSharp/GameSharp/Windowing/Window.cs:line 11
   at Program.<Main>$(String[] args) in /home/shadowblitz16/Documents/source/C#/GameSharp/GameSharp/Program.cs:line 2
```

**Comment by jasonswearingen** [comment]
are you building from source?   if so, you need to copy the libraylib.so from https://github.com/NotNotTech/Raylib-CsLo/tree/main/Raylib-CsLo/runtimes/linux-x64/native  into your build directory.

**Comment by SB16Tech** [comment]
> are you building from source? if so, you need to copy the libraylib.so from https://github.com/NotNotTech/Raylib-CsLo/tree/main/Raylib-CsLo/runtimes/linux-x64/native into your build directory.

no I use the nuget package

**Comment by jasonswearingen** [comment]
sorry but the reports I have heard over the last months is that  linux x64  works.  what version of raylib-cslo are you using?

sorry I don't use linux so can not independently verify.

**Comment by SB16Tech** [comment]
> sorry but the reports I have heard over the last months is that linux x64 works. what version of raylib-cslo are you using?
> 
> sorry I don't use linux so can not independently verify.

I was using the one from nuget with .net 7
